# Generated by Django 3.1 on 2020-09-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('date_registered', models.DateTimeField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images')),
                ('is_deleted', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateTimeField()),
                ('street', models.CharField(max_length=50)),
                ('barangay', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('spouse_name', models.CharField(max_length=100)),
                ('spouse_occupation', models.CharField(max_length=50)),
                ('no_of_children', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
