# Generated by Django 3.1 on 2020-10-09 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_auto_20201008_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 18, 5, 58, 900934)),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 18, 5, 58, 900934)),
        ),
    ]
