# Generated by Django 3.1 on 2020-10-09 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20201009_1805'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_of_transaction',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 18, 5, 58, 916294)),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='movie_id',
            field=models.ManyToManyField(related_name='Movie', to='movie.Movie'),
        ),
    ]
