# Generated by Django 3.1 on 2020-10-09 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20201009_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_of_transaction',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 20, 12, 7, 290765)),
        ),
    ]
