# Generated by Django 3.1 on 2020-10-11 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20201009_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_of_transaction',
            field=models.DateField(default=datetime.datetime(2020, 10, 11, 9, 55, 25, 742007)),
        ),
    ]
