# Generated by Django 3.1 on 2020-10-11 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20201011_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_of_transaction',
            field=models.DateField(default=datetime.datetime(2020, 10, 11, 10, 2, 16, 187032)),
        ),
    ]
