# Generated by Django 3.1 on 2020-09-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField()),
                ('sku', models.CharField(max_length=50)),
                ('genre', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateTimeField()),
                ('director', models.CharField(max_length=100)),
                ('casts', models.TextField()),
                ('price', models.FloatField()),
                ('no_of_items', models.IntegerField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            options={
                'db_table': 'dvd',
            },
        ),
    ]
