# Generated by Django 3.1 on 2020-09-23 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('date_registered', models.DateField(default=datetime.datetime(2020, 9, 23, 10, 20, 49, 176179))),
                ('genre', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField(default=datetime.datetime(2020, 9, 23, 10, 20, 49, 176179))),
                ('director', models.CharField(max_length=100)),
                ('casts', models.TextField()),
                ('price', models.FloatField()),
                ('no_of_items', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='cover_image/default.png', null=True, upload_to='cover_image')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
        migrations.DeleteModel(
            name='Dvd',
        ),
    ]
