# Generated by Django 3.1 on 2020-09-23 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200923_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2020, 9, 23, 10, 23, 53, 85290)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 23, 10, 23, 53, 85290)),
        ),
    ]
