# Generated by Django 3.1 on 2020-10-08 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200923_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 20, 17, 4, 488224)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 20, 17, 4, 488224)),
        ),
    ]
