# Generated by Django 3.1 on 2020-10-09 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20201009_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 20, 12, 7, 280832)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 20, 12, 7, 281830)),
        ),
    ]
