# Generated by Django 3.1 on 2020-10-11 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20201009_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2020, 10, 11, 9, 55, 25, 736993)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 11, 9, 55, 25, 736993)),
        ),
    ]
